# -*- coding: utf-8 -*-
"""Quiz Play using CLI and GUI program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHqJ1PGoYoXhiYEQQh88G-nqxLqHeBMX
"""

#<<<< Calling json module to permit read and write of data in JSON format>>>>>
import json,os

#<<< function inputInt() is called with prompt to prompt input until int is given>>>
def inputInt(prompt):
    while True:
        try:
            temp = int(input(prompt))    
            return temp
        except:
            continue

#<<<<< function inputSomething() is called with prompt to prompt all intil but till whitespace appears>>>
def inputSomething(prompt):
    global data_list
    question = input(prompt)
    return question

#function saveChanges() is called with source list and it coverts the same in JSON format>>>>
def saveChanges(dataList):
    with open('/content/drive/MyDrive/data.txt', 'w') as outfile:             # w stands for write
        json.dump(dataList, outfile)

#<<< Welcome statement>>>>>>
print('Welcome to the Quiz')

with open('/content/drive/MyDrive/data.txt','r') as data_file:    
    data_text_file = json.load(data_file)
current_ques_list = []
while True:

    data_list = []
    print('Choose [a]dd, [l]ist, [s]earch, [v]iew, [d]elete or [q]uit.')
    choice = input('> ').strip()
    try:
        if(type(choice)!='str'):
            raise Exception
    except Exception:
        if choice == 'a':
            # Add a new question.
            
            question = str(inputSomething("Enter the question: ").strip()).lower()
            while True:
                if(question == ""):
                    question =str(inputSomething("Enter the question: ").strip()).lower()
                else:
                    break


            answer = []
            while True:
                x = str(input("Enter a valid answer (enter 'q' when done):").strip()).lower()
                if(x==''):
                    continue
                elif(x!='' and x!='q'):
                    answer.append(x)
                elif(x=='q' and len(answer)!=0):
                    break
                
            temp = inputInt('Enter question difficulty (1-5)')
            while True:
                if(temp < 1 or temp >5):

                    print("Invalid value. Must be an integer between 1 and 5")
                    temp = inputInt('Enter question difficulty (1-5)')
                else:
                    break

            
            diff = temp
        
            final_object = {'question':question,'answer':answer,'diff_level':diff}
            data_list.append(final_object)
            current_ques_list.append(final_object)
            if(os.stat("/content/drive/MyDrive/data.txt").st_size == 0):
                saveChanges(data_list)
            else:
                #with open('data.txt','r') as data_file:    
                #    data = json.load(data_file)

                #print(data_text_file)
                for i in data_list:
                    data_text_file.append(i)
                saveChanges(data_text_file)
            
        
        elif choice == 'l':
            # List the current questions.
            if(len(current_ques_list)==0):
                print("No questions saved")
            else:
                print("Current Question:")
                for i in range(0,len(current_ques_list)):
                    print('\t',i+1,")",current_ques_list[i]['question'])    



        elif choice == 's':
            # Search the current questions.
            search_term = inputSomething("Enter a search term: ").strip()
            
            
            for i in range(len(current_ques_list)):
                if search_term in current_ques_list[i]['question']:
                    print("Search results:")
                    print('\t',i+1,')',current_ques_list[i]['question'])
        


        elif choice == 'v':
            # View a question.
            view_index = inputInt('Question number to view: ')
            
            try:
                req_data = current_ques_list[view_index-1]
                print("Question:")
                print("\t",req_data['question'])
                print("\t","Valid Answers: ",', '.join(req_data['answer']))
                print("\t","Difficulty: ",req_data["diff_level"])
                
            except:
                print("Invalid index number")

            

        elif choice == 'd':
            # Delete a question.
            try:
                del_index = int(inputInt('Question number to delete: '))-1
                if(del_index+1>len(current_ques_list)):
                    print("Invalid index number")
                else:
                    del_question = current_ques_list.pop(del_index)
                    
                    #saveChanges(current_ques_list)
                    
                    #with open('data.txt','r') as data_file:    
                    #    temp_list = json.load(data_file)
                    #print(data_text_file)
                    for i in range(len(data_text_file)):
                        if(data_text_file[i]['question']==del_question['question']):
                            del data_text_file[i]
                    
                    
                    
                    try:
                        #print('try',data_text_file)
                        with open('data.txt', 'w') as outfile:
                            json.dump(data_text_file, outfile)
                    
                    except:
                        print("Invalid index number")
            except:
                pass



        elif choice == 'q':
            # Quit the program.
            # See Point 8 of the "Requirements of admin.py" section of the  brief.
            print("GoodBye!")
            break



        else:
            # Print "invalid choice" message.
            # See Point 9 of the "Requirements of admin.py" section of the  brief.
            print("Invalid choice")
            continue

